# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20160823_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
