# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20160828_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.CharField(max_length=1300),
        ),
    ]
