# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20160829_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_image',
            field=models.FileField(upload_to=b''),
        ),
    ]
