# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=50)),
                ('playlist_author', models.CharField(max_length=50)),
                ('playlist_date', models.CharField(max_length=50)),
                ('playlist_image', models.CharField(max_length=1500)),
                ('playlist_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Playlist')),
            ],
        ),
    ]
